CREATE DATABASE IF NOT EXISTS aplis_db;
USE aplis_db;

CREATE TABLE IF NOT EXISTS medicos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    CRM VARCHAR(50) NOT NULL,
    UFCRM VARCHAR(2) NOT NULL
);

CREATE TABLE IF NOT EXISTS pacientes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    dataNascimento DATE,
    carteirinha VARCHAR(100),
    cpf VARCHAR(14) NOT NULL
);